# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen"
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false

[[prune.project]]
name = "k8s.io/code-generator"
unused-packages = false
non-go = false

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"

# Our master branch tracks knative/pkg master or a release.
[[override]]
  name = "knative.dev/pkg"
  branch = "master"

# needed because pkg upgraded
[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"
