apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: functions-controller
rules:
- apiGroups:
  - functions.knative.dev
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - serving.knative.dev
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - update
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - list
  - watch